version: '3'

services:
  myalert:
    container_name: myalert
    image: registry.cn-hangzhou.aliyuncs.com/tenbayblockchain/myalert:1.0
    restart: always
    hostname: myalert
#    privileged: true
    environment:
      ALERT_LIST: SCU27294T0d8657096c7ecebaf6b903ac504040b05b0f63d87d365
      ALERT_URL: https://raw.githubusercontent.com/kh682/w/master/alert.json
      LOG_LEVEL: DEBUG
      MAX_DISK_PERCENT: 92
      MAX_CPU_PERCENT: 92
      MAX_MEM_PERCENT: 92
      CHECK_INTERVAL: 10
      REPORT_INTERVAL: 30
      ALERT_TITLE: "机器告警"
    logging: {driver: "json-file", options: {max-size: "10m", max-file: "10"}}
