version: '3'

services:
  sshd:
    container_name: sshd
    image: sshd:latest
    restart: always
    hostname: sshd
    network_mode: host
    environment:
      - SSHD_OPTION=
        -o "PermitRootLogin no"
        -o "AuthorizedKeysFile .ssh/authorized_keys"
        -o "AllowUsers guest"
        -o "ClientAliveInterval 15"
        -o "ClientAliveCountMax 3"
        -o "PubkeyAuthentication yes"
        -o "StrictModes no"
        -o "PasswordAuthentication no"
        -o "GatewayPorts clientspecified"
      - SSHD_PORT=12334
    logging: {driver: "json-file", options: {max-size: "10m", max-file: "10"}}
    volumes:
        - ./data/sshd/authorized_keys:/home/guest/.ssh/authorized_keys
    command: /docker-entrypoint.sh